Version: "3"
services:

  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_DATABASE: patient
      MARIADB_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mariadb_native_password
    ports:
      - "3306:3306"
    networks:
      - patient_network
    volumes:
      - db_data:/var/lib/mariadb
  app:
    container_name: patient
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: patient
      DB_USER: root
      DB_PASSWORD: root
      AUTH_PLUGIN: mariadb_native_password
    depends_on:
      - db
    networks:
      - patient_network

networks:
  patient_network:

volumes:
  db_data:
